export const Colors = {
  'primary-green': '#689C36',
  'secondary-black': '#191A19',
  'text-gray': '#ACADAC',
  verify: '#8A8A8A',
  'btn-white': '#F2F5F0',
  'input-bg': '#F3F6F2',
  error: '#DF2E2E',
  'light-mode': '#FFFFFF',
  'dark-mode': '#191A19',
  'light-green': '#E6F8D5',
  'neutral-white': '#F7FFFA',
  'product-gray': '#FCFFFD',
  success: '#E6F8D5',
};
